// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYn76MR3XZFI-m7nzMXi-zZUNF0M-4m_8',
    appId: '1:674932196424:web:cf0b79062b876242d6c47d',
    messagingSenderId: '674932196424',
    projectId: 'poc-passkey',
    authDomain: 'poc-passkey.firebaseapp.com',
    storageBucket: 'poc-passkey.firebasestorage.app',
    measurementId: 'G-27GRT2LWTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkQVHFnP7nh1K4-GFMouowCyM2RvrAFl0',
    appId: '1:674932196424:android:9aaf8ae31315c44fd6c47d',
    messagingSenderId: '674932196424',
    projectId: 'poc-passkey',
    storageBucket: 'poc-passkey.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA13gg_gpAokkjUACZyZdxSS8qD09pTuS0',
    appId: '1:674932196424:ios:3ab6f5593d88d363d6c47d',
    messagingSenderId: '674932196424',
    projectId: 'poc-passkey',
    storageBucket: 'poc-passkey.firebasestorage.app',
    iosBundleId: 'com.staffinc.passkeypoc',
  );
}
